// Generated by Wrangler by running `wrangler types --experimental-include-runtime=./runtime.d.ts`

interface Env {
  CHAT_SESSIONS_STORAGE: KVNamespace
  MY_VARIABLE: 'production_value'
  API_KEY: string
  BOT_KEY: string
}
