// Generated by Wrangler
// After adding bindings to `wrangler.jsonc`, regenerate this interface via `npm run cf-typegen`
interface Env {
	API_KEY: string;
	BOT_KEY: string;
	CHAT_SESSIONS_STORAGE: KVNamespace;
}

export interface Context {
	session?: any;
}
