export const emojis = [
	{ type: 'emoji', emoji: '👍', name: 'Thumbs up' },
	{ type: 'emoji', emoji: '👎', name: 'Thumbs down' },
	{ type: 'emoji', emoji: '❤️', name: 'Red heart' },
	{ type: 'emoji', emoji: '🔥', name: 'Fire' },
	{ type: 'emoji', emoji: '🥰', name: 'Smiling face with 3 hearts' },
	{ type: 'emoji', emoji: '👏', name: 'Clap' },
	{ type: 'emoji', emoji: '😁', name: 'Big smile' },
	{ type: 'emoji', emoji: '🤔', name: 'Thinking face' },
	{ type: 'emoji', emoji: '🤯', name: 'Exploding head' },
	{ type: 'emoji', emoji: '😱', name: 'Face screaming in fear' },
	{ type: 'emoji', emoji: '🤬', name: 'Abusing face' },
	{ type: 'emoji', emoji: '😢', name: 'Crying face' },
	{ type: 'emoji', emoji: '🎉', name: 'Party popper' },
	{ type: 'emoji', emoji: '🤩', name: 'Star-struck' },
	{ type: 'emoji', emoji: '🤮', name: 'Vomiting face' },
	{ type: 'emoji', emoji: '💩', name: 'Poop emoji' },
	{ type: 'emoji', emoji: '🙏', name: 'Praying' },
];
